      - name: Install all dependencies
        run: |
          npm install
          cd server && npm install
          cd ../client && npm install

      - name: Verify installations
        run: |
          echo "Root node_modules:"
          ls -la node_modules/ | head -5
          echo "Client node_modules:"
          ls -la client/node_modules/ | head -5
          echo "Checking for react-scripts:"
          ls -la client/node_modules/.bin/ | grep react-scripts || echo "react-scripts not found"

      - name: Build React app
        run: |
          cd client
          npm run build
