# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - XYZ-wallet

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'
  AZURE_WEBAPP_NAME: 'xyz-wallet-app'  # Update this to your actual App Service name
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            server/package-lock.json
            client/package-lock.json

      - name: Install root dependencies
        run: npm ci

      - name: Install server dependencies
        run: |
          cd server
          npm ci

      - name: Install client dependencies
        run: |
          cd client
          npm ci

      - name: Verify installations
        run: |
          echo "Root node_modules:"
          ls -la node_modules/ | head -5
          echo "Server node_modules:"
          ls -la server/node_modules/ | head -5
          echo "Client node_modules:"
          ls -la client/node_modules/ | head -5
          echo "Checking for react-scripts:"
          ls -la client/node_modules/.bin/ | grep react-scripts || echo "react-scripts not found"

      - name: Build React app
        run: |
          cd client
          npm run build
        env:
          CI: false
          GENERATE_SOURCEMAP: false

      - name: Verify build output
        run: |
          echo "Build directory contents:"
          ls -la client/build/
          echo "Checking for index.html:"
          ls -la client/build/index.html || echo "index.html not found"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME || env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Verify deployment
        run: |
          echo "Deployment completed successfully!"
          echo "App URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"